name: Env Var
on:
  push:
    branches:
      - qa
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      # Build using SAM
      - run: aws lambda update-function-configuration --function-name my-function \--environment "Variables={BUCKET=my-bucket,KEY=file.txt}"
